// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZY7dfau5CWLaiR0GKOhPZwe9H6RSkhG0',
    appId: '1:820100932299:web:6880389d77c8d1be0e714e',
    messagingSenderId: '820100932299',
    projectId: 'minimal-chat-app-c1cf4',
    authDomain: 'minimal-chat-app-c1cf4.firebaseapp.com',
    storageBucket: 'minimal-chat-app-c1cf4.firebasestorage.app',
    measurementId: 'G-2G8B8C15ML',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZLZdEVtvHNJQ3_9yLos4tezTAvQskFbY',
    appId: '1:820100932299:android:f402e1590da0f5b90e714e',
    messagingSenderId: '820100932299',
    projectId: 'minimal-chat-app-c1cf4',
    storageBucket: 'minimal-chat-app-c1cf4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9Y2HKsiVijiAI-66bBf7aJly0Bt2MCg8',
    appId: '1:820100932299:ios:c56e46e8a579df650e714e',
    messagingSenderId: '820100932299',
    projectId: 'minimal-chat-app-c1cf4',
    storageBucket: 'minimal-chat-app-c1cf4.firebasestorage.app',
    iosBundleId: 'com.example.minimalChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9Y2HKsiVijiAI-66bBf7aJly0Bt2MCg8',
    appId: '1:820100932299:ios:c56e46e8a579df650e714e',
    messagingSenderId: '820100932299',
    projectId: 'minimal-chat-app-c1cf4',
    storageBucket: 'minimal-chat-app-c1cf4.firebasestorage.app',
    iosBundleId: 'com.example.minimalChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZY7dfau5CWLaiR0GKOhPZwe9H6RSkhG0',
    appId: '1:820100932299:web:f28da70a8db893d80e714e',
    messagingSenderId: '820100932299',
    projectId: 'minimal-chat-app-c1cf4',
    authDomain: 'minimal-chat-app-c1cf4.firebaseapp.com',
    storageBucket: 'minimal-chat-app-c1cf4.firebasestorage.app',
    measurementId: 'G-LZS6Y7956Z',
  );
}
